apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: backend-ci-run
spec:
  pipelineRef:
    name: backend-ci
  params:
    - name: git-url
      value: "https://github.com/SAl0nKA/onpk"
    - name: git-revision
      value: "main"
    - name: docker-image-repo
      value: "salonka/onpk-appbackend"
    - name: image-tag
      value: "latest"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  serviceAccountName: pipeline-sa
