apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: frontend-cd-run
spec:
  pipelineRef:
    name: frontend-cd
  params:
    - name: git-url
      value: "https://github.com/SAl0nKA/onpk"
    - name: git-revision
      value: "main"
    - name: release-name
      value: "frontend-app"
    - name: namespace
      value: "default"
    - name: image-tag
      value: "latest"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  serviceAccountName: pipeline-sa
