apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: {{ .Values.services.frontend.service.type }}
  ports:
    - port: {{ .Values.services.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
   app: frontend
