apiVersion: apps/v1
kind: Deployment
metadata:
  name: appbackend
  labels:
    app: appbackend
spec:
  replicas: {{ .Values.services.backend.replicaCount }}
  selector:
    matchLabels:
      app: appbackend
  template:
    metadata:
      labels:
        app: appbackend
    spec:
      containers:
        - name: appbackend
          image: {{ .Values.services.backend.image.repository }}:{{ .Values.services.backend.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.services.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
          {{- with .Values.services.backend.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /ok
              port: http
          readinessProbe:
            httpGet:
              path: /ok
              port: http
